---
- name: Deploy deployments on Kubernetes
  hosts: masters
  gather_facts: false
  become: true

  tasks:

    # ---------------------------------------------Tomcat-----------------------------------------------------------
    # Vérifier si le le deployement existe déjà sur le namespace pre-prod
    
    - name: Vérifier l'existence du deployement Tomcat
      shell: kubectl get deployment tomcat-deployment
      ignore_errors: true
      register: pod_check_result

    # Créer le deployement Tomcat sur le namespace pre-prod si il n'existe pas 
    - name: Créer le deployement Tomcat
      shell: kubectl create -f /home/trainee/kubernetes/service_applicatif/tomcat-deployment.yaml
      when: pod_check_result.rc != 0

    # Services Tomcat

    # Vérifier si le services pour posgres existe déjà sur le namespace pre-prod
    - name: Vérifier l'existence du service Tomcat
      shell: kubectl get service tomcat-service
      ignore_errors: true
      register: pod_check_result

    # Créer le service Tomcat sur le namespace pre-prod 
    - name: Créer le service Tomcat
      shell: kubectl create -f /home/trainee/kubernetes/service_applicatif/tomcat-service.yaml
      when: pod_check_result.rc != 0
